services:
  - type: web
    name: khydro-flow-station-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://yillotmxhrchjvslgvym.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_xydgPFAE_mWsyDJYnawu1g_yzJDOCR_

