services:
  - type: web
    name: khydro-flow-stations-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
